version: "3"

services:
  testnet:
    build:
      context: ./packages/contracts/
      dockerfile: ../../containers/Contract.dockerfile
    ports:
      - "5000:5000"
  coordinator:
    build:
      context: ./
      dockerfile: ./containers/Coordinator.dockerfile
    ports:
      - "8888:8888"
    links:
      - 'testnet:testnet'
    command: 'node /proj/packages/coordinator/dist/cli/index.js --ws ws://testnet:5000 --config /proj/packages/coordinator/coordinator.json'
