version: '3.4'

services:
  contracts:
    image: zkoprunet/contracts:fix-249
    build:
      context: ../packages/contracts/
      dockerfile: ../../dockerfiles/Contract.dockerfile
  contracts-for-integration-test:
    image: zkoprunet/contracts-integration-test:fix-249
    build:
      context: ../packages/contracts/
      dockerfile: ../../dockerfiles/Contract.integration.dockerfile
  circuits:
    image: zkoprunet/circuits:feat-239
    build:
      context: ../packages/circuits/
      dockerfile: ../../dockerfiles/Circuits.light.dockerfile
  playground:
    image: zkoprunet/playground:feat-239
    build:
      context: ../
      dockerfile: dockerfiles/Playground.dockerfile
  coordinator:
    image: zkoprunet/coordinator:fix-249
    build:
      context: ../
      dockerfile: dockerfiles/Coordinator.dockerfile
